"""create rental_items and maintenance_log

Revision ID: b235442fb49a
Revises: 
Create Date: 2026-09-10 07:06:57.261199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b235442fb49a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_log',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.Enum('lane', 'shoe', 'ball', name='targettype'), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('maintenance_type', sa.Enum('clean', 'inspection', 'repair', 'replace', name='maintenancetype'), nullable=False),
    sa.Column('maintenance_category', sa.Enum('daily', 'regular', 'sudden', 'legal', name='maintenancecategory'), nullable=False),
    sa.Column('status', sa.Enum('not_started', 'in_progress', 'completed', name='maintenancestatus'), nullable=False),
    sa.Column('repair_method', sa.Enum('in_house', 'vendor', name='repairmethod'), nullable=True),
    sa.Column('vendor_name', sa.String(), nullable=True),
    sa.Column('performed_by', sa.String(), nullable=True),
    sa.Column('cost', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('action_date', sa.Date(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_maintenance_log_log_id'), 'maintenance_log', ['log_id'], unique=False)
    op.create_table('rental_items',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.Enum('shoe', 'ball', name='itemtype'), nullable=False),
    sa.Column('size_or_weight', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('in_stock', 'rented', 'inspecting', 'repairing', 'suspended', 'disposed', name='itemstatus'), nullable=False),
    sa.Column('acquired_at', sa.Date(), nullable=True),
    sa.Column('maintenance_frequency_days', sa.Integer(), nullable=True),
    sa.Column('next_maintenance_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_rental_items_item_id'), 'rental_items', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rental_items_item_id'), table_name='rental_items')
    op.drop_table('rental_items')
    op.drop_index(op.f('ix_maintenance_log_log_id'), table_name='maintenance_log')
    op.drop_table('maintenance_log')
    # ### end Alembic commands ###
